### ISSUE TITLE
Switch from GCM to FCM

### ISSUE THREAD

**Issue by akentosh** [puterstructions/wtfdiw-mobile#15]
We are currently using google cloud messaging and need to switch to firebase cloud messaging.

**Comment by bfowle** [comment]
This is done and tested.

Of course it's not smooth sailing as a particular branch/fork has to be used for the v2 version of the `phonegap-plugin-push`; relevant tracking here: https://github.com/phonegap/phonegap-plugin-push/issues/929
This branch works properly on its own, but the way `ionic state...` works, it errors out because it doesn't understand specific-branch syntax (reponame#branch). So to get CI to work a `ionic plugin add...` had to be done after the `state restore`.
Once this branch is merged and a v2 release cut it should work without hacks.

TODO (split into new cards?):
- FCM has a notion of 'topics' similar to WS channels... instead of sending to a list of device ids one can subscribe and publish to topics instead -- this is likely the approach we'll need to take; the server is just looping the devices in the list and sending individual msgs, not great (but works)

Please read up on: https://firebase.google.com/docs/cloud-messaging/

**Comment by n8behavior** [comment]
Working, needs documentation

**Comment by nparry** [comment]
Moved notifications to the client so this is obsolete
